### ISSUE TITLE
Change supported versions in plugin's page

### ISSUE THREAD

**Issue by TheIronMinerLv** [kangarko/CoreArena#131]
If you cannot provide full support for <1.13 versions (physical engine - one of main points plugin's advertising is based upon), then change it and don't fool your customers.

It is sad that physical engine only supports 1.13 now, as you might now, 1.13 is soooo unstable (1.13.1 too), so many CoreArena buyers will stay on one version with few issues (that are fixed in newer plugin versions) for a long time.

**Comment by kangarko** [comment]
Please use 1.7.2 for physical engine on Minecraft 1.7.10 till 1.12, or the latest version for 1.13.1.

Here is the honest truth:

The reason is that WorldEdit has updated massively, and since many classes have the same names or methods but give different results we cannot even import two different WorldEdit version to hook, and reflection would be insanely slow when replacing 100k arena blocks so we rather decided to only support the latest version of that plugin.

Thank you for your understanding.

**Comment by TheIronMinerLv** [comment]
Well, don't say it is impossible - other plugin authors manage to create "modules" for their plugins, you could make Worldedit module (for Physical engine and stuff) as additional jar or whatnot to drag and drop, in such way providing support to both versions (2 separate modules, one for 1.7-1.12, other for 1.13).

But... by seeing how slowly you add brand new stuff (your "roadmap" is more than a year old, yet none of them is implemented), this won't happen anyway.
