### ISSUE TITLE
Arena restoring weird

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#157]
On CoreArena 1.7.15, Arenas restore really weirdly with stairs and other blocks. We are also using worldedit version `7.0.0-SNAPSHOT;3950-b192466` 

Snapshot was made on 1.12.2 and restored on 1.13.2

**Comment by kangarko** [comment]
I am sorry but that is caused by WorldEdit changed the schematic from 1.12 to 1.13.2. Lots of code has been changed so I am grateful that it remained working at least in such state, see https://medium.com/@Me4502/updating-3-of-the-largest-minecraft-plugins-in-existence-to-1-13-be3485ef2c16

I recommend you place the schematic on a test 1.12 server on a world, than load the world on your 1.13 server and copy it from there.
