### ISSUE TITLE
Toggle baby spawning

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#159]
It would be nice if monster spawners had a setting on them that toggled whether they spawned baby mobs or not. No way to manage them at the moment and can lead to baby mobs getting spawned in phases that you don't want them to be spawned in.

**Comment by kangarko** [comment]
Hey Wrangler,

thank you for your suggestion. Since CoreArena already supports the Boss plugin, I am not planning to use it. If you have Boss already you can just place a Boss egg with a Baby Boss inside of the spawner. If not, we will be having sales through-out Christmas so that maybe something you can benefit from.

Thank you,
Matej
