### ISSUE TITLE
[bug] StackOverflowError when trying to use the "Clone monster spawnpoint" tool.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#16]
Created my first monster spawn point, went to copy it with the tool and it stack overflowed.
https://pastebin.com/7unXp1nm

**Comment by kangarko** [comment]
Hey!

I am sorry to hear that, can you please help me out to solve this quickly?

* What MC version are you using?
* How exactly did you click or manipulated with the tool?

**Comment by kangarko** [comment]
Hello!

You're right, I have spent time investigating this and unfortunately the bug lies in how Bukkit serializes the itemstack (the spawn egg), more specifically its metadata. I have tried to workaround it but was unsuccessful. 

For now, no more error is produced, instead, you'll get a warning about that custom monsters eggs such as those from BOSS or MythicMobs may not have been cloned properly.

**Comment by FrozenBeard** [comment]
So the clone tool doesn't work then? and I have to continue to make them manually? Why not when cloning read the name of the egg so you know what it is, then you can re-create the egg in your own storage method using the MythicMobs calls? There has to be an API for it.

**Comment by kangarko** [comment]
The clone tool works just fine unless a custom egg is used. The issues goes deeper (I used +2h on it)

We use Google's GSON library for serializing the spawner information. The ItemStack itself can easily be serialized by calling the 'serialize' method, and so does the ItemMeta class. 

Such serialized items are available as a HashMap which is further translated into a JSON string stored in the tool.

The problem occurs when we attempt to deserialize the 'ItemMeta' class from Bukkit. It simply does not contain the necessary methods and attempting to use reflection to access CraftMetaItem class where the methods are found appears to be broken (from my testing). I have implemented those reflection calls in the next version, you can test it and maybe you'll find a different result (Boss vs. MythicMobs).

I cannot program the serialization myself for each possible field in ItemMeta and ItemStack myself. Even if there was a public API we couldn't re-call the bosses that way due to how they are stored.

**Comment by FrozenBeard** [comment]
Thats way above my head! I'll take your word for it, as long as you are looking for a solution, im happy.
