### ISSUE TITLE
Few issues/questions

### ISSUE THREAD

**Issue by Roran2** [kangarko/CoreArena#193]
I recently discovered an error that will not let me create an initial snapshot of my arena to take advantage of the procedural damage - https://pastebin.com/ahynQrbm
I haven't really experienced this issue before so I am hoping that you will be able to kind of crack what is going on here.
Also, I was wondering if this plugin supports the ability to create signs with stats, such as the top player w/ pve kills, or most levels, ect.

**Comment by Roran2** [comment]
Also ran into this: https://pastebin.com/reHaEm8E while creating upgrades. It seems I can't create more than one, and if I delete the second upgrade it becomes usable again, but when creating a second upgrade after that, just repeats the error.

**Comment by kangarko** [comment]
Hey, sorry for a late response, please grab the latest version of WorldEdit from http://builds.enginehub.org/job/worldedit/last-successful?branch=master

Currently we don't have statistic signs but that is something we have on our road map :)

The second error I believe was fixed in the recent update, let me know if you still have it.
