### ISSUE TITLE
MythicMob Support

### ISSUE THREAD

**Issue by xNocSx** [kangarko/CoreArena#2]
Hello, Here are the first issues!
**1)** The Spawning Tools Doesn't work properly (neither with MythicMob's Eggs nor Vanilla Mob's Eggs);
**2)** Redstone doesn't hide after the Dungeon Start;
**3)** Power Signs don't hide after the Dungeon start;
**4)** After the first phase Power Signs pop out begin replaced for a second from a RedStone Block.
After That they'll not be placed back and they works as a normal drop item. This happens every phase.
After the dungeon ends, the sign is blank and there is no way to restore the previous "text" (not a big problem tbh).

## **_Pastebin with a bunch of errors!_**

https://pastebin.com/vZLEShi8

**Comment by kangarko** [comment]
Hey, thank you for your report, I'll address is in the morning.

**Comment by kangarko** [comment]
Hey, I am actually on holidays in different country, I can't access the workplace as I need. Please mind a few days. I am coming back 14th of July (don't worry we'll fix it way earlier).

**Comment by kangarko** [comment]
Hello,

1. Which Spawning Tools? From CoreArena? If so, how exactly do they not work and how they should?

2. Redstone is not supposed to be hidden automatically.

3. The signs cannot be hidden due to limitations in the server redstone processing.

4. Yes that's perfectly normal. There's no way around it, again due to limitations in the server itself.

Which sign is blank after the dungen starts?

I have fixed around half of the errors from your pastebin. Will fix the rest in 1-2 days. **Until then please do not use custom spawner eggs in your monster spawners**.

Thank you for reporting!

**Comment by xNocSx** [comment]
Hello there,
I've only used the "Iron block one" adding Vanilla Eggs or MithycMobs Eggs.
When i close the GUI, in console says that "There isn't any valid eggs" or something like that.
When i re-open the GUI there isn't any egg.
Only if i close the GUI  (letting it empty with no Eggs) it Saves.
If i add Eggs it doesn't Save because it doesn't recognize eggs.

If you want i can make you an YT Video to explain it much better :)

**Comment by kangarko** [comment]
Yes please! Currently the plugin does not accept any kind of eggs that are not naturally available from the creative inventory, meaning no eggs from third party plugins work. This is planned and will be added soon.

**Comment by kangarko** [comment]
Hey @xNocSx, I have been working on MythicMobs support and it should now be available. Please test out the version 1.1.0. I am closing this, but please comment below if you experience any problems.
