### ISSUE TITLE
FastAsyncWorldEdit Support

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#21]
Average sized arenas freeze all players when they are loaded by the first player, as the entire area is loaded in one go, this is utter insanity of design when FAWE exists.
https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/
They have an API too, **USE IT!** There is no reason not too. 

I have pasted multiple region sized schematics in seconds using FAWE with NO lag, NO Freeze no nothing. It just works, its free, its got an API, its fast.

Where are the snapshots saved for CoreArena?

**Comment by kangarko** [comment]
I will get back to make CoreArena and Puncher compatible with FAWE.

We store snapshots in WorldEdit/schematics folder using the same name as your arena, and <arena>_damaged.schematic file for the damaged snapshot.

**Comment by FrozenBeard** [comment]
I was literally going to request for saving into the WE folder! I didn't notice as I use FAWE which creates a folder for the user to save their schematics in, Ive been creating a region in WG (For easy selection) and saving a copy of before and after damage manually, and then also running its snapshot feature.  As its a massive pain in the ass to make changes to an arena once you have made a snapshot.

If I were to save over these with a //schem save Arena & //schem save Arena_damaged, would this do the same task as the snapshot feature? or is some other data saved when doing that?

**Comment by LogGits** [comment]
Yes! This is fantastic!

**Comment by kangarko** [comment]
If you were to select the region with //pos1 and //pos2, then //copy it and save using //schem, this is exactly the same as we do via in-game menu.

### FAWE Integration Progress

I got into FAWE integration. There is no such code that would do the exactly same task as we do in FAWE, because FAWE listens for WorldEdit and overrides it, as specified on the Wiki:

`Firstly, FAWE isn't meant to modify the behavior of the WorldEdit API. Existing code should run faster simply by having FAWE installed`

From my testing in-game (32 view-distance and 1 GB ram), (big) arenas were loaded **lag-free** with FAWE:
![https://i.imgur.com/3QYwCjM.png]

### Conclusion
CoreArena and Puncher use FAWE automatically and do not need a specific hook. The only problems in my testing were occasional lightning issues where one or two chunks were completely dark.

What is your experience?

**Comment by LogGits** [comment]
Block physics don't work with fawe. When they do get launched it is invisible and the users don't see it but when they walk over a block that was displaced invisibly they start glitching into the block. It doesn't show the block was moved on the clients screen.

**Comment by kangarko** [comment]
CoreArena does not use WorldEdit at all in procedural damage. WorldEdit is only used when starting or finishing an arena to restore the arena map. The damage spawns a FallingBlock normally using Bukkit API.

I have opened a ticket at https://github.com/boy0001/FastAsyncWorldedit/issues/809, please post there your server and FAWE version and the fawe debug command as per their issues guidelines. Thank you.

**Comment by bc-hill** [comment]
I am facing a similar issue, with [AsyncWorldEdit](https://github.com/SBPrime/AsyncWorldEdit).
The actual copy/pasting of the arena works fine, it is just the procedural damage that is a problem.  No blocks fly, fall, or catch on fire.  This still occurs if AsyncWorldEdit is disabled via in-game commands.  Only not loading the jar is the answer.
I will contact the developer of AWE, as he [seems prepared to deal with this](https://github.com/SBPrime/AsyncWorldEdit/wiki#plugin-x-stopped-working-after-installing-awe), but maybe there is also something that you can do, since this is occurring with multiple plugins?
Thank you!

**Comment by kangarko** [comment]
Hey, sorry I am not planning to expand support for AsyncWorldEdit. Please consider using **Fast**AsyncWorldEdit instead.

**Comment by FrozenBeard** [comment]
As someone who also bought AsyncWorldEdit and moved to FastAsyncWorldEdit, its SO much better, which is annoying since its free.

**Comment by bc-hill** [comment]
Hello, I can see your point, however:
- These are not identical plugins.
- Both plugins have a large established user base.

In my personal case, AsyncWorldEdit has exactly what I need.  FAWE has what I need, plus a ton of other features that I don't want (The first line on the Spigot page says "Over 200 Commands.")  More features = more possible bugs or potential conflicts with other plugins in the future.  Not that it is a conclusive indicator of anything, but AsyncWorldedit is 1.9MB, and FAWE is 5.4MB, which seems to support my feeling that FAWE has a lot of "bloat" that I don't need.

What change was required for the FAWE fix, that would be a problem with AsyncWorldEdit?

Thank you!

**Comment by FrozenBeard** [comment]
@bc-hill But FAWE works better at ASYNC tasks, like Its, much, much better. You don't need to use all of its features, its not going to slow your server down lol It only runs the WE tasks when you execute them, and it does a better job than AsyncWorldEdit, I know I used AsyncWorldEdit for years and I moved to FAWE about 6 months ago, it destroys AsyncWorldEdit in performance, and it even works with Voxel Sniper.

**Comment by bc-hill** [comment]
As I said, I understand.  But at this point, I have reported an incompatibility, and been told too bad, use a different plugin.  I will need an explanation at least, as to why it cannot be implemented.  I love CoreArena already, but it is the newcomer to my server, and will not be telling established (conflict-free) plugins to go away.

**Comment by kangarko** [comment]
Oddly enough, the following line solved all issues with maps in FAWE:
![a](https://i.imgur.com/qIQZZrl.png)

Correct me if I am wrong, but both plugins wrap up the WorldEdit API and listen for its EditSession _automatically_. CoreArena only uses WorldEdit, which is caught by each of those plugins and modified. Thus I cannot easily solve this issue otherwise. 

Nevertheless, I have contacted the author of AWE personally and gave him all WorldEdit code from CA/Puncher. I will be looking forward for a possible fix in the near future.

**Comment by kangarko** [comment]
Closing, FAWE is supported long time ago.
