### ISSUE TITLE
How i can use?

### ISSUE THREAD

**Issue by fish500m** [kangarko/CoreArena#219]
I bought this plugin because I wanted to have fun with my friends.
But I installed GameAPI and CoreArena, but it doesn't work.
I'm using version 1.11.2 and I've tried both Spigot and Paper. Can I get more help?

**Comment by CaptnSisko** [comment]
I'm not the developer but I don't think you've provided enough relevant information for anyone to help you. Please see the "What we need to know" section of the wiki (https://github.com/kangarko/CoreArena/wiki/Getting-Help-the-Right-Way#what-we-need-to-know) for some guidelines. Specifically...

In what way does the plugin "not work"? Do you get an error when you try to execute certain commands? Does the game not start? Does the plugin not load at all?

How did you install the plugin? Did you use /reload instead of restarting the server properly?

Are there any errors that show up in the logs related to this plugin?

What is the output of /version?

What is the output of /plugins?

What version of Corearena and GameAPI are you using? ("latest" is not a version) Is the version of Worldedit you're using compatible with 1.11.2?

**Comment by fish500m** [comment]
![image](https://user-images.githubusercontent.com/48436847/60763165-856de600-a0a9-11e9-94a0-96b9139a7a10.png)

**Comment by CaptnSisko** [comment]
Looks like Corearena isn't enabled. Are you getting any errors when you start the server?

**Comment by fish500m** [comment]
Maybe.

**Comment by fish500m** [comment]
Can you give me the bucket that you use?

**Comment by CaptnSisko** [comment]
Please upload a log of your server starting up using pastebin or by uploading a log file

**Comment by fish500m** [comment]
I was successful when I tried it again slowly. Thank you for your answer!

**Comment by kangarko** [comment]
I understand that the plugin loads up fine right now, closing.

If not, please upload the latest.log file from logs/ over to uploadfiles.io after stopping the server with CoreArena malfunctioning and post the link here.
