### ISSUE TITLE
[Request] SQLite database key to convert to MySQL

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#22]
I need to move my SQLite database to MySQL, I tried opening it up in http://sqlitebrowser.org/ and  its asking for a password, I cant see this anywhere in the configs. Can I know the password so I can open the database to export it to MySQL, then I can import all my arena settings into the MySQL without having to re-make the arena from scratch.
https://www.dropbox.com/s/erlgkfe5selicyi/Screenshot%202017-11-01%2016.50.07.png?dl=0

**Comment by kangarko** [comment]
Hey,

I am sorry but I personally have no experience in that and I believe that, what you are asking for, is irrelevant for this plugin. CoreArena only stores Nuggets for players in the MySQL database. CoreArena does not stores nor uses SQLite.

All information regarding the connection to MySQL is defined by you, there is no password for me to give you because it is you who configure it in "MySQL" in settings.yml

**Comment by FrozenBeard** [comment]
Yeah I noticed this afterwards! I assumed all data was saved in the .db file, I created my mysql database and let the users start from scratch with their nuggets in the end.
