### ISSUE TITLE
Gamemode in Arena

### ISSUE THREAD

**Issue by TNG-China** [kangarko/CoreArena#226]
Hi @kangarko

How can i set gamemode to adventrue in arena?

Scordborad casue lag in Autoplay, 
Why you give up this plugin, Most of your plugins in my network, but it broken, so sad

**Comment by kangarko** [comment]
Hello,

CoreArena has been designed to operate in the survival gamemode. It is currently not possible to change it.

I am sorry about AutoPlay! However we're a very small team and were not catching up this year, people had to wait sometimes 7 days to get support so we had to remove 2 plugins. It's better this way otherwise we would remove CoreArena.

AutoPlay is no longer supported, you can disable its scoreboard for now.
