### ISSUE TITLE
Bug spawn monsters

### ISSUE THREAD

**Issue by MrSuricate2** [kangarko/CoreArena#237]
Hello,
[I give you my server so you can watch the bug that I encounter with my different boss spawn place.](https://drive.google.com/file/d/1FgunMbZOuTlXPjBARH6ZbchSwAbqBWW-/view?usp=sharing)
The green wool means that all the monster wave spawn.
The blocks of redstone made spawn a boss "elder_gardian" every 5 waves. At different places as there is no "every" option that exists.
When I configure the plugin all goes well but when I'm playing the mob boss does not spawn and is replaced by other mobs.
I remain at your disposal

**Comment by kangarko** [comment]
Hello,

I don't need to see the whole server, I only need to see your CoreArena folder. The file is too large/won't download for some reason, just ZIP me your CoreArena/ folder here directly.

What mobs is the Elder Guardian replaced by?

Matej

**Comment by MrSuricate2** [comment]
Hello,

The elder guardian and replace by mobs that are managed by other spawn location.

Example: spawn "A" I have 3 skeleton spawn
and at spawn "B" I want an elder guardian.

the spawn "B" will make spawn 3 skeleton.

[I join you the file / CoreArena](https://drive.google.com/open?id=1ZpQmR0KUbCw4O2qP8Dfb5H5-roZvVXIX)

**Comment by kangarko** [comment]
I think I start to understand, so you want the spawn point B spawn 1 elder guardian, but instead, 3 skeletons are spawned from the same spawn point.

Ensure the spawner only contains 1x elder guardian egg and that is configured to run exactly on phase 5. Also note that the arena wont spawn more monsters if they reach the max arena limit (that you have on 100 and 2000 for Desert).

You can also set **Debug** option to **[spawning]** in **settings.yml** and let me know what the console says when the arena spawns 3 skeletons instead of 1 elder guardian. Thank you.

**Comment by MrSuricate2** [comment]
https://pastebin.com/31V67UG0

**Comment by MrSuricate2** [comment]
[debug.log](https://github.com/kangarko/CoreArena/files/3638679/debug.log)

line 447

**Comment by kangarko** [comment]
It says "Picked entity to spawn: {count=4, entity=SKELETON}" which means you have multiple entities in the spawner.

Only put Elder Guardian into Monsters menu in the spawner. Create a new spawners for Skeletons and only use this one for Elder Guardian. 

The spawner always chooses one monster randomly from all eggs you have put into it.

**Comment by MrSuricate2** [comment]
The problem is that in the generator I put only Elder Guardian egg and no skeleton egg.
Where then I do not understand what you wanted to tell me

**Comment by kangarko** [comment]
That's really odd! Well there's one more solution on the table and that is actually if I download your part of the server as you sent me the first time so I can text on your exact setup. I know you did this the day 1 but I never could test because I couldn't get the file, if you only send me the world I will boot it up as it is thanks!

Can you upload me your world "DAF" with your arena as well?

**Comment by MrSuricate2** [comment]
I join you the DAF world and the CoreArena folder.

[CoreArena.ZIP](https://github.com/kangarko/CoreArena/files/3658914/CoreArena.ZIP)
[DAF.ZIP](https://github.com/kangarko/CoreArena/files/3658918/DAF.ZIP)

**Comment by kangarko** [comment]
I have wondeful news, I have rewritten the spawning logic and from now on your arena will spawn elder guardians on phase 5 correctly! 

Thank you for patiently waiting.
