### ISSUE TITLE
placeholders

### ISSUE THREAD

**Issue by MothGirlMusic** [kangarko/CoreArena#246]
what are the placeholders? trying to make a leaderboard uo of the highest kills or something

**Comment by kangarko** [comment]
Hey,

unfortunately there are at present no variables to use outside of CoreArena. We are planning to integrate this feature in the future.

**Comment by MothGirlMusic** [comment]
any way in the plugin to make a leaderboard sign or something?

**Comment by kangarko** [comment]
No sorry, but please describe me in details how you'd like this to work and I'll go ahead and put this into our roadmap.

If there's another plugin you like as an inspiration, you can refer to it as well.

**Comment by kangarko** [comment]
I added the variables {corearena_nuggets}, {corearena_is_playing} and {corearena_class} that show the amount of Nuggets a player has, a true/false output if they are currently playing, and finally their class or nothing if they haven't yet selected a class in the arena they play in.

The other variables are currently not possible since we're not tracking those statistics yet.
