### ISSUE TITLE
Suggestion to use AsyncWorldedit

### ISSUE THREAD

**Issue by Cerexus** [kangarko/CoreArena#248]
We would really like it if you could at async WE support. Its not that hard, i used it myself the last days in my plugin. 

I think others would like it too.

**Comment by Cerexus** [comment]
Its hard to find a good API Documentation, this should be enough for that feature. 

https://github.com/SBPrime/AsyncWorldEdit/issues/244

The Arena should also be closed while the Map is restoring. 

Hope you do that :)

**Comment by kangarko** [comment]
Have you tried FastAsyncWorldEdit yet? We're planning to integrate AWE as well but I can't give you an ETA.

**Comment by Cerexus** [comment]
Nah FAWE has no official release for 1.14 while AWE has. Thats also the reason why i used AWE in my plugin otherwise i would use FAWE..  But if the devs from FAWE needs months to upgrade the plugin..  We both know that this is too long :D

**Comment by kangarko** [comment]
To be honest, we're a 1 man's team for some time now, but I've put this into our todo list and once we start rebuilding we'll integrate it!

**Comment by benevolent2012** [comment]
Has AWE integration been added to the plugin? It seems to lag the server behind every time I use it.

https://pastebin.com/eR7an3nL

**Comment by LeehamElectronics** [comment]
> Has AWE integration been added to the plugin? It seems to lag the server behind every time I use it.
> 
> 
> 
> https://pastebin.com/eR7an3nL

I'm currently using AWE 3.7.3 with worldedit 7.2.0 beta01 
Everything works fine with this setup but only sand/gravel blocks "fly" and have gravity when using the CoreArena damage physics. I'm going to try CoreArena 2.7.6 later today and see if it makes any difference. At the moment I also receive large lagg spikes and massive TPS drops whenever some leave or joins an arena due to the way arenas reset. I'm not sure why because I'm testing using the DAF map that came with the plugin but I'm gonna do some tests today with different versions and combinations of world edit and I'll let you know what works best for me in case you wanna try it to. I also want to try the latest version of AWE but it requires WorldEdit 7.2.0 beta 02 which I can't find anywhere, does anyone have a link to where you can download beta 02? Bukit website only lets me download beta 03 which doesn't work with AWE.

To be honest I don't think it's CoreArena's code causing the lag or the "physics" to only work on sand / gravel, it's just a matter of getting the right combo of world edit / AWE or FAWE but iether way the dev is working rly hard to get it all working and I'm sure it will be fixed soon. See the issue I made on GitHub just recently for more info.

**Comment by LeehamElectronics** [comment]
UPDATE: (see the issue I pinned for more info on versions)
I got procedural damage and CoreArena latest version working well with AWE and WorldEdit. However I agree that there is still lag spikes and tps drop when joining an arena but it's good enough for now. It works really great in game once started with very little lag!

**Comment by benevolent2012** [comment]
Yes, CA works with AWE and WE.  However, like you mentioend, when joining the arena, corearena causes a thread deadlock, so the server thread literally just freezes, along with the massive TPS drop, which makes it impractical for any server to use.

Using FAWE works fine for initial snapshot recovery, except there's way too many little bugs with FAWE, I would much prefer to use AWE if possible.

The thread deadlock and the massive global tps drop is a huge issue with CA. Since I don't have the source code, I can't really look into exactly how CA deals with WE either... so we need @kangarko 's help!

**Comment by kangarko** [comment]
Unfortunately I have no control over AWE causing the deadlock. I will be looking into completely taking over arena snapshots in the next major CoreArena release, meaning no WorldEdit will be needed. No ETA.

**Comment by LeehamElectronics** [comment]
> 
> 
> Unfortunately I have no control over AWE causing the deadlock. I will be looking into completely taking over arena snapshots in the next major CoreArena release, meaning no WorldEdit will be needed. No ETA.

Thanks Matej, I look forward to this, I hope it is a priority because using snapshots is impossible on servers due to the dead lock. 
Cheers
