### ISSUE TITLE
bug experience

### ISSUE THREAD

**Issue by MrSuricate2** [kangarko/CoreArena#252]
Hello,
When I kill two mobs the items that gives the xp stack in one. but when the player picks up the item that gives the xp this wins only 1 xp.

Example:
my items that drop when I kill a mob is a bottle of experience.
When I kill a creeper I earn 10 XP each
I kill 2 creepers the bottles stack in one and I only earn 10 XP.

**Comment by kangarko** [comment]
Hello,

It seems like your server is configured to stack up those items. We cannot track those changes since there is no event for merging items nor a suitable way to track them.

I recommend you move your arena into a "minigame" world and write a new option to your spigot.yml file at world-settings.minigame.merge-radius.item section with the value of 0.0 to disable item stacking on your world completely.

If you use an anti-lag plugin you will have to disable it from there.
