### ISSUE TITLE
Procedural Damage may not be honouring BARRIER blocks?

### ISSUE THREAD

**Issue by pseud0** [kangarko/CoreArena#257]
Hello,
During initial design of a couple of different arenas I have attempted to implement the procedural damage by way of the snapshot function inside of CoreArena.  

What I have noticed is that CoreArena may not actually be honouring "barrier" blocks when calculating whether or not to inflict damage in a particular area.  

I have had areas of my map use the barrier block and for the pre and post snapshots the barrier blocks have existed in both.  However during gameplay the barrier blocks seem to get destroyed, causing my players to fall through the floor and into parts of the map that are otherwise out of bounds. 

Could you please confirm your code caters for all blocks including barrier blocks?

**Comment by kangarko** [comment]
Hello!

By which means were the barrier blocks destroyed? After using The Explosive Bow, TnT or something else?

All of the other means of destroying an arena other than The Explosive Bow apply the natural Minecraft behavior. The Explosive Bow is calculated separately. When its arrow explodes, we check each blocks in the explosion radius for its version from the destroyed snapshot.

So by theory it should preserve barriers when you have them exactly on the same spots on both damaged and initial snapshots. The same goes for the other means of explosions since I believe Minecraft never destroys them in an explosion.

Just to be sure you can build a wall 5 barrier blocks thick and then test to which degree it gets destroyed. I know you wrote that both snapshots have the barrier blocks but do really test this is the case in a per-block basis otherwise they will get removed upon explosions by The Explosive Bow.

I hope that helped!
