### ISSUE TITLE
1.16.2: MythicMobs Health Bar Problem

### ISSUE THREAD

**Issue by jiajunmao** [kangarko/CoreArena#341]
Issue observed: Mythicmobs' healthbars persist even after the arena terminates and the mob is removed.

Investigation done: /mm mobs kill <mob_name> will clear the health bar from clients if spawned and killed independent of CA. However, including that into the commands that get executed after the arena ends/finishes in arena.yml yields no successful result and cause the health bar to stay.

**More investigation: even /kill @e[type=<mob_type>] will remove the health bar, wondering what CA executes at the end of the arena to remove all the mobs.

Possible cause: CA kills the mob at the end of the arena prior to executing the commands, and somehow that doesn't player well with mythic mobs' health bars.

**Comment by LeehamElectronics** [comment]
Are you using the latest dev builds of MythicMobs?

**Comment by jiajunmao** [comment]
Yeah I am

**Comment by kangarko** [comment]
Hi there,

We simply call Entity#remove method as specified in Bukkit API.

![a](https://i.imgur.com/pVoOmlg.png)

I am afraid there is little I can do since we are only relying on Bukkit to do the cleanup. Please refer this to MythicMobs authors as they should be the ones responsible for cleaning their leftovers properly. All plugins removing entities from worlds are most likely affected by this, not just CoreArena.
