### ISSUE TITLE
Spectate Mode

### ISSUE THREAD

**Issue by Hellcode48** [kangarko/CoreArena#361]
1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
A spectate mode would allow players to spectate people fighting wave after wave of enemies and watch the players suffer! (JK on the suffer part of course, but it would be nice to sit back and spectate)

2) What would happen if we won't implement this feature? How's your server being affected?
We would all be super sad but would still use the plugin, my server would have depression tbh.

3) If suggesting something new - Can the old system be modified/improved instead?
You can put them into spectator mode but make it where they cant go out of the arena bounds, create a leave command too

**Comment by LeehamElectronics** [comment]
This has already been requested but we'll see what Matej says.

**Comment by LeehamElectronics** [comment]
Actually we don't really need Matej to implement this anyway, you can simply use plugins like UltraCustomizer and WorldGaurd along with commands that run for example when a player clicks on a join spectators NPC. All you need to do is have an NPC that runs 2 commands, puts user into spectate mode, then teleports them to a multiverse anchor that you can make somewhere inside the arena.
Alternatively you can use a plugin called UltraCustomizer (this is what I'm doing), make a item GUI with each arena and a sub menu and another item that automates the two commands I mentioned before, it may take it bit longer, but with plugins like UltraCustomizer its super easy to setup.
https://www.spigotmc.org/resources/ultra-customizer.49330/

Let me know if this helps! @Hellcode48

**Comment by Hellcode48** [comment]
I'd rather just have Metej implement a spectator function that's usually in mob arena plugins anyways (you kinda expect mob arena plugins to have this feature out of the box rather than jump through hoops)

**Comment by LeehamElectronics** [comment]
> 
> 
> I'd rather just have Metej implement a spectator function that's usually in mob arena plugins anyways (you kinda expect mob arena plugins to have this feature out of the box rather than jump through hoops)

I understand, however at present I think Matej is very busy with ChatControlPro and other plugins so this is probably the best work around for now, also I feel like there are other priorities for CoreArena such as replacing nuggets with Vault and so forth, so if you have time, see if you can implement the method I mentioned above.

**Comment by LeehamElectronics** [comment]
Also check the road map and software review guide as most improvements are mentioned there already that Matej is aware of:
https://github.com/kangarko/CoreArena/issues/4

**Comment by Hellcode48** [comment]
Whoa, what do you mean replace nuggets with vault? I like the idea of a different currency type for the arena plugin. Will that feature be able to be turned off?

**Comment by LeehamElectronics** [comment]
I am hoping Matej will ad it as an option in settings.yml so you can toggle between using nuggets or just using Vault for currency, This is extremely important as I outlined here:
https://github.com/kangarko/CoreArena/issues/353
In summary, if I could use vault instead, I would be able to fully Customize everything about CoreArena with my plugins such as ShopGUI+ and UltraCustomizer and so forth. Possibilities are endless if we can use Vault.

Take this as an example, players save up their Mini-games currency by playing CoreArena and my other mini games since they all use vault, then once they get enough coins, they can unlock premium Arenas for CoreArena by using my Shop GUI which checks and takes money from their Vault account and if they have enough coin, it gives them the permission node they need to join the "Premium Arena"

Its customization like this that just is not possible with Nuggets if you understand.

**Comment by kangarko** [comment]
Thanks, right now we have other priorities such as the one Leeham mentioned. When CoreArena is being rewritten then we'll add a native spectate mode.

**Comment by LeehamElectronics** [comment]
Perfect, and if anyone else is wondering, I just setup CoreArena spectating on my mini games server using command NPC's and UltraCustomizer and it works really well! U can even use CoreArenas "command in arena end" in the arena.yml to automatically teleport the spectators out of the arena at the end.

Probably don't even need Matej to add this since it's already possible and only took me 10 min to setup. PM me if u need more help!
