### ISSUE TITLE
1.16.2: Allow the user to upgrade items via a GUI?

### ISSUE THREAD

**Issue by brandcrystal** [kangarko/CoreArena#380]
Signs are really outdated, can we allow GUIS for the mid-game item upgrades!

Thank you!

**Comment by LeehamElectronics** [comment]
Hey there, I have been using GUI's with CoreArena thanks to plugins such as UltraCustomizer:
https://www.spigotmc.org/resources/ultra-customizer.49330/
Please look into this if you want to make GUI's or improve CoreArena overall. As for signs, you can pretty much replace the sign functionality by using UItraCustomizer, take the red-stone sign as an example. You could make a GUI that runs a script that places a red-stone block somewhere to enable something inside your arena, the possibilities are endless. You can also just have commands run inside your arena.yml such as //fill to automate this too.

The only thing I am unsure about is the 'Upgrade' sign on the wiki, what does that actually do? Also it talks about 'Puncher' on the wiki for teams, what actually is Puncher @kangarko  ? I have no idea what it is or where to find it.

I hope I could help @brandcrystal , You should definitely checkout UltraCustomizer, it can be really handy for plugins like CoreArena.

**Comment by LeehamElectronics** [comment]
Also I have partly already mentioned this here @brandcrystal  https://github.com/kangarko/CoreArena/issues/353
As you can see, if Matej adds normal Vault economy to CoreArena instead of nuggets, you could even use plugins such as ShopGUI+ to make your own CoreArena shops including in game upgrade shops too.

- Liam

**Comment by brandcrystal** [comment]
I would love to chat with you over on Discord, maybe you could help me! Thank you very much! 

branflake#6059

**Comment by LeehamElectronics** [comment]
I will send u a DM

**Comment by LeehamElectronics** [comment]
Ahh I now understand what the Upgrade sign is for, I can see how this would be useful because it will encourage players to kill mobs so they can purchase items in game. Very cool. I cant really see a way of using the amount of XP / levels a player has in my Shop GUI because levels are not a currency, however, by using UltraCustomizer I can use their API to create a custom addon and script for CoreArena. All I would need is some of the code open sourced relating to the levels a player has.

Perhaps Matej could allow us to call a function like corearena.getplayerXP(playername) 
Then I can simply write a script such as 
if corearena.getplayerXP(playername)  >= item_price:
   Give player item
else:
   dont give item, sendMessage("You dont have enough XP to purchase this!")

**Comment by LeehamElectronics** [comment]
Actually now that I think about, I can probably just use the player XP placeholder lol. Ill see what I can come up with by using UltraCustomizer when I have time.

**Comment by LeehamElectronics** [comment]
**UPDATE:**
Using a GUI for in game purchases and upgrades inside an arena is already possible, using ShopGUI+ I can make items purchasable with the amount of XP / levels a player has! However it would still be nice to remove nuggets and just have vault, but this certainly works for now! 

- Liam

**Comment by LeehamElectronics** [comment]
https://github.com/kangarko/CoreArena/issues/381 @brandcrystal  I have tested it and it works, you can make GUI's for players while they are in an arena for them to shop. However the issue is that CoreArena and vanilla XP / levels are out of sync as I outlined in the issue mentioned. 

Here is a pic of my CoreArena shop that I made if you want some ideas:
https://imgur.com/a/L3rsb1e

I hope that was helpful.

**Comment by kangarko** [comment]
Thanks Leeham for taking this up, I am interested in adding this into CoreArena natively in the future :)
