### ISSUE TITLE
Regarding open source and new dev....

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#391]
I'm more than a little bit concerned that this plugin has become "open source" and you're looking for someone to take over the project.
I know you gotta do what you gotta do, but can we at least get some information about what will happen to this plugin? It wasn't exactly cheap.

A while back I saw people talking about how this plugin will be discontinued, but then you changed your mind and kept working on it. that gave me hope for this plugin and was a large part in leading me to buy it the other day.
I just bought this plugin days ago, but I've spent much of the past 5 months building my server. Also I've already grown attached to this plugin. It feels like I'm at risk to losing a piece of my soul here.

I don't know if I'm the only person here who is confused, but I really would like some info.
My assumption is that you want to drop this project because it's not as popular as some of your other projects, and because your team is small it is a better choice to work on less projects. So you want to find a new person to take over this project.
(If any of that is inaccurate, please fill us in)

1.
What exactly does it mean that the plugin is "open source" now?
2.
What do you mean that you can't guarantee updates after december 5th 2021 (for example, will the plugin be discontinued if you can't find someone to take it over by that time, if the new guy also drops the project then there's nothing you can do about it?)?
3.
Can we still expect regular updates to the plugin until december 5th 2021?
4.
What exactly does the future of this plugin look like from now on, and how will that affect us (the buyers)?
5.
Is there any chance for you to change your mind and continue leading this project?

**Comment by LeehamElectronics** [comment]
1. It means of all its code is available for free so you can add your own features to CoreArena and fix your own bugs!
2. idk, I think the new guy will still be working for Matej, so if the new guy drops it im guessing Matej just takes it back...
3. I hope
4. I think for now it looks fine, the fact that its open source is great cause we can add our own stuff to it.
5. I like the way Matej does things, hopefully he does change his mind.

**Comment by KasearMC** [comment]
> 1. It means of all its code is available for free so you can add your own features to CoreArena and fix your own bugs!

but i don't know how to code...
does this also mean that other people are able to use the code for this plugin to post their own arena plugin on spigotmc and other places?

**Comment by LeehamElectronics** [comment]
I don't think they can "re sell" the plugin after making changes due to copy right, but anyone can fork the code "copy it" and make changes and share it for everyone to use. I have already made a fork of CoreArena on my GitHub that you can look at, I haven't made any changes yet as I am finishing off my final year schooling. U can however just learn java and make your own fork if u want to get into software development. It's pretty fun

**Comment by kangarko** [comment]
1. It means everyone can access it.
2. Unfortunately due to life situation I cannot guarantee keeping CoreArena after that date, means you'll get no support
3. Now that's open source it means that everyone can update it freely at will.
4. The future is, after said date, I will no longer be a position (nor I am right now) where I can maintain so many plugins effectively and I'll drop CoreArena, I sincerely apology for the inconvenience.
5. Ties back into 4.
