### ISSUE TITLE
[major bug] Nuggets dupe if you swap servers quickly.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#40]
So as I was told to do, I setup Corearena on both my Survival and my Events server, the game runs on the events server and the survival just uses corearena to pull the nuggets from the database so players can buy rewards using their nuggets.

Issue: If a player spends their nuggets on survival and quickly swaps back to the events server then back to the survival, they get their nuggets back, and they can just repeat this. I assume its some form of cache, why the hell is it not updating once they spend them? this is a major flaw in logic.

I also noticed that I joined my survival once and my nuggets said 0, but when I joined my events and then came back to survival the nuggets were there! 

There is some serious issues with your nugget system.

**Comment by kangarko** [comment]
Hello,

I am sorry you have issues (again). I just run a testing with two servers connected over bungeecords connection, and unluckily to me everything was working fine (see image 1). In order to help you as quick as possible, please do me a quick favor and enable the "mysql" debugger as per Image 2. Whenever this will happen again the console will tell you the Nuggets on both servers so you can see where the plugin failed, and I can fix it right away. I cannot fix it now because I don't know where to start and have exams that's why I need a little testing on your side. Thank your for your understanding.

Image 1:
![a](https://i.imgur.com/zmLDwSg.jpg)

Image 2:
![a](https://i.imgur.com/ORseJJH.png)

**Comment by FrozenBeard** [comment]
see #29 for more info.

**Comment by kangarko** [comment]
Continuation of the issue mentioned above.
