### ISSUE TITLE
1.16.4: Custom items with effects

### ISSUE THREAD

**Issue by Ciredex** [kangarko/CoreArena#410]
Hi!
On my Server, i have many custom Items, that give you for example more HP when you have it in the offhand. Now when you join the arena you have those more HP in the arena too, even you dont have the item. When you leave the arena, you keep these HP and get those from the custom item.
I set the config Store_Inventories: false, but now the players XP does not get stored as well.
Is it possible to set the XP store true, even tho the inventory is not stored? Or that the Bug with the HP created by the custom items gets fixed?
-Ciredex

**Comment by kangarko** [comment]
Sorry I'm afraid that's an incompatibility with your custom item.

**Comment by enterih** [comment]
That would affect every item that have modified attributes. It's not one customitem; it's everything who chance the health.

The problem is
Player has a Iron_helmet with + 2 Life (20HP + 2 = 22HP)
Player joined the arena and player has without the item 20HP
Player leaved the arena and get the inventory back. The plugin mean: The player had 22HP (instead of 20) and set it to 22
Player has now 24hp (22HP +2HP from the Item). The player can do that again and again and again

You see that problem?`I'm sure with your knowledge you will can fix it easy. I would be ready to donate for the plugin when this could be fixed.

**Comment by kangarko** [comment]
CoreArena is on bug-fix maintenance only and its code is open source, anyone can make contributions without needing donating
