### ISSUE TITLE
1.16.5: Server restart while arena is running causes inventory loss and player position loss.

### ISSUE THREAD

**Issue by Vehzx** [kangarko/CoreArena#413]
1.16.5: Server restart when in the arena causes inventories to not load on rejoin.

When playing in an arena, you use one of the kits, for me this is Tank, Rouge, Ranger.

If the server restarts while a player is in the arena (my server restarts every 6 hours), when a player rejoins they lose their inventory because the plugin stops when the server restarts.

Is there anyway around this? This is a big issue because the player not only doesn't TP back to their location from where they joined with /ma join, but they also lose their inventory they had and are given the kit from the arena instead.

I don't believe I need to give my plugin folder for this.

**Comment by kangarko** [comment]
Thanks, however I don't believe there's an easy fix right now because we simply don't get the time to save these inventories because the player is getting kicked out and we only get one call to save it while the server has already saved the map earlier. So you can either kick everyone and then restart the server.
