### ISSUE TITLE
unable to set waiting lobby or save snapshot

### ISSUE THREAD

**Issue by frizzbee30** [kangarko/CoreArena#8]
Hi, spigot 1.12 latest commit

latest build of corearena, issues persists on upgrade of version

getting this on our test server

https://pastebin.com/ygBVvfDL

it wouldn't allow me to use the spade to set the waiting lobby, and then running a snapshot save failed.

We do use Fast Async World edit, which it appears to be complaining about in the error log?

Thanks :)

**Comment by frizzbee30** [comment]
Just to add that plugin appears to load normally with no errors shown in the log

**Comment by kangarko** [comment]
Hello,

I just tested it with FAWE and must conclude that this plugin is at the moment partially uncompatible. It works the worse the larger the arena is, because it'll mess up the lightning and if players join the arena before the loading is finished they may get stuck or see the arena as black.

I'll be contacting his developer but I cannot promise anything atm, sadly.

* For the first error, this will be fixed in the next version. I apology for the inconvenience.
* For the other errors, they don't come from CoreArena but from worldedit loading the clipboard. Make sure you have the latest dev build (http://builds.enginehub.org/job/worldedit/last-successful?branch=master). If not please remove saved snapshots (from plugins/WorldEdit/schematic/ folder it is <arena>.schematic and <arena>_damaged.schematic files)

**Comment by frizzbee30** [comment]
Thanks for investigating, we aren't running the arenas in live as yet, but obviously would like to at some point as it's a pretty fantastic plugin!

:D

**Comment by kangarko** [comment]
Glad to hear! I am closing this right now but please keep me updated in whatever questions you have or potential issues and we'll solve them :)
