### ISSUE TITLE
Teleport command player argument + Arena command question

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#85]
Current teleport command is `/ma teleport <arena>`. It would be convenient if there was a player argument in there e.g. `/ma teleport <arena> [player]` [player] would be optional to teleport a player to that arena.

Also when the arena doesn't start because there are too many players, can this have a seperate command system like:
```yaml
  Insufficient_Players: 
    Player: []
    Console: []
```
Currently it runs Player_leave but i want to use different things for leave and insufficient players. Loving the plugin, keep up the great work!

**Comment by kangarko** [comment]
Hey,

thanks for your suggestion!

Do you have a basic Java skills? Since CoreArena/Puncher use GameAPI you could easily listen to the ArenaPostStopEvent and check for the cause CANCELLED_NOT_ENOUGH_PLAYERS. It would make it so much easier for you to customize arenas to your need. Same for the teleport command.

I am actually preparing a full course on how to make Java plugins, so if you're interested keep an eye on my profile messages.

**Comment by LogGits** [comment]
This is a feature that should be in the plugin itself, not a custom plugin that hooks into it. It all comes down the the customisability of the plugin, this is one of the many reasons that sets corearena apart from other arena plugins.

**Comment by kangarko** [comment]
Sure, I see. Well right now I am prioritizing smaller/easier features and bug fixes because I am busy with the course, but I will return to it ;)

**Comment by kangarko** [comment]
We are not planning to include this feature due to works on other priorities.
